### ISSUE TITLE
DatabaseDumpReader error?

### ISSUE THREAD

**Issue by mikehuhsf** [Zoltanar/Happy-Reader#9]
Whenever I try to use DatabaseDumpReader, I get a error message that says:  System.IO.FileNotFoundException: Could not find file 'C:\Users\Michael\AppData\Roaming\Happy Reader\Database Dumps\vndb-db-2023-11-20\db\releases_lang'.

Is there a way to fix this?

**Comment by Zoltanar** [comment]
This was fixed in commit 72c153efdf340f79a402dae6bf61c51032b31b4f.  
Unfortunately as the VNDB Database Dump is not a stable public API, most changes to its structure require changes in the consuming code, however, these changes are not that common.
I haven't created a release in a while, and there's a lot of improvements since last release, so I'll aim to create a new release rather than patch the latest one, please wait for that.

**Comment by Zoltanar** [comment]
[New release](https://github.com/Zoltanar/Happy-Reader/releases/tag/v2.6.0) is out now.
